/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx,ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#adc6ff',
        'on-primary': '#002e69',
        'primary-container': '#4b8eff',
        'on-primary-container': '#00285c',
        'primary-fixed': '#d8e2ff',
        'primary-fixed-dim': '#adc6ff',
        'on-primary-fixed': '#001a41',
        'on-primary-fixed-variant': '#004493',
        'inverse-primary': '#005bc1',

        'secondary': '#53e16f',
        'on-secondary': '#003911',
        'secondary-container': '#05b046',
        'on-secondary-container': '#003a11',
        'secondary-fixed': '#72fe88',
        'secondary-fixed-dim': '#53e16f',
        'on-secondary-fixed': '#002107',
        'on-secondary-fixed-variant': '#00531c',

        'tertiary': '#ffb874',
        'on-tertiary': '#4b2800',
        'tertiary-container': '#d47b00',
        'on-tertiary-container': '#412200',
        'tertiary-fixed': '#ffdcbf',
        'tertiary-fixed-dim': '#ffb874',
        'on-tertiary-fixed': '#2d1600',
        'on-tertiary-fixed-variant': '#6a3b00',

        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',

        'background': '#10131b',
        'on-background': '#e0e2ed',
        'surface': '#10131b',
        'on-surface': '#e0e2ed',
        'surface-dim': '#10131b',
        'surface-bright': '#363942',
        'surface-container-lowest': '#0b0e16',
        'surface-container-low': '#181c23',
        'surface-container': '#1c2028',
        'surface-container-high': '#272a32',
        'surface-container-highest': '#31353d',
        'surface-variant': '#31353d',
        'on-surface-variant': '#c1c6d7',
        'surface-tint': '#adc6ff',
        'inverse-surface': '#e0e2ed',
        'inverse-on-surface': '#2d3039',
        'outline': '#8b90a0',
        'outline-variant': '#414755',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        unit: '4px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '24px',
        gutter: '16px',
        margin: '24px',
        'container-padding': '20px',
      },
      fontFamily: {
        'display-lg': ['Inter', 'sans-serif'],
        'display-lg-mobile': ['Inter', 'sans-serif'],
        'headline-md': ['Inter', 'sans-serif'],
        'title-sm': ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'label-caps': ['Inter', 'sans-serif'],
        'data-mono': ['JetBrains Mono', 'monospace'],
      },
      fontSize: {
        'display-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'display-lg-mobile': ['24px', { lineHeight: '30px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'title-sm': ['18px', { lineHeight: '24px', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
        'data-mono': ['13px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
};
